# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e625fd2fcd9b91276998b067c20a0325a0dcfa96e3691898bb54f72755c01c2deefaa51b8e368c277c06ecfd6c935c7172e5054d85c082f3b1524e6bd0a7d865

test:
  secret_key_base: 50b38a157d953e7deb65f62a500058f7bce238389d1e75d95cc495d5bae46c7b69b42dbbc1437d432b2bc08697862ae248e388e4cef01b1ec63b4530c49962dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
